---
- name: Execute command and display output
  hosts: azure
  gather_facts: no
  tasks:
    - name: Execute ls /etc
      command: ls /etc
      register: etc_output

    - name: Display output
      debug:
        var: etc_output.stdout
